### ISSUE TITLE
css

### ISSUE THREAD

**Issue by elimsc** [elimsc/blog#3]
### 布局
1, float & clear 
https://www.youtube.com/watch?v=xara4Z1b18I

2, position: static, relative, absolute, fixed
https://alistapart.com/article/css-positioning-101

3, flex布局
http://www.ruanyifeng.com/blog/2015/07/flex-grammar.html

4, grid布局

### css选择器
https://learn.shayhowe.com/advanced-html-css/complex-selectors/

### 元素显示

**Comment by elimsc** [comment]
https://learn.shayhowe.com/advanced-html-css/complex-selectors/

后代选择器

| Example| Classification|Explanation |
| :------- | :-------- | :---------- |
| `article h2` |Descendant Selector | 所有后代 |
| `article > p` | Direct Child Selector | 直接后代 |

兄弟选择器

| Example| Classification|Explanation |
| :------- | :-------- | :---------- |
| `h2 ~ p` |General Sibling Selector| h2后的所有同级p |
| `h2 + p` | Adjacent Sibling Selector | 毗邻且在h2后的一个p |


属性选择器 `a[target]`

| Example| Classification|Explanation |
| :------- | :-------- | :---------- |
| `a[href="http://google.com/"]` | Attribute Equals Selector | `href="http://google.com/"`的 a  
| `a[href*="login"]` | Attribute Contains Selector |  `href` 值包含 `login` 的 a
| `a[href^="https://"]` | Attribute Begins With Selector |  `href` 以 `https://` 开头的 a
| `a[href$=".pdf"]` | Attribute Ends With Selector | `href`属性以 `.pdf` 结束的 a

伪类选择器

| Example| Classification|Explanation |
| :------- | :-------- | :---------- |
| `a:link` |Link Pseudo-class| 未点击的链接 |
| `a:visited` |Link Pseudo-class | 已点击的链接 |
| `input:enabled` | State Pseudo-class | 可用的input |
| `input:disabled` | State Pseudo-class | 不可用的input |
| `input:checked` | State Pseudo-class | 被选中的`checkbox`或`radio`

**Comment by elimsc** [comment]
缩写
```css

.box {
  background: #2db34a;
  border-radius: 6px;
  transition: background .2s linear, border-radius 1s ease-in 1s;
}
.box:hover {
  color: #ff7b29;
  border-radius: 50%;
}
```

完整写法 `transition-property`, `transition-duration`, `transition-timing-function`, `transition-delay`

```css
.box {
  background: #2db34a;
  border-radius: 6px
  transition-property: background, border-radius;
  transition-duration: .2s, 1s;
  transition-timing-function: linear, ease-in;
  transition-delay: 0s, 1s;
}
.box:hover {
  background: #ff7b29;
  border-radius: 50%;
}
```

**Comment by elimsc** [comment]
![image](https://user-images.githubusercontent.com/13717100/57267967-9eabe380-70b4-11e9-8ef4-8456e94392c8.png)

父元素（容器）
```css
.box {
    display: flex;
}
// flex-direction    主轴的方向
// flex-wrap
// flex-flow
// justify-content  主轴上的对齐方式
// align-items   交叉轴上的对齐方式
// align-content  多根轴线上的对齐方式
```

子元素（项目）
```css
.item {
}
// order
// flex-grow
// flex-shrink
// flex-basis
// flex
// align-self
```

**Comment by elimsc** [comment]
### box-shadow
- box-shadow 前四个参数：`x 偏移值`、`y 偏移值` 、`模糊半径`、`扩张半径`。
- 单侧投影的核心是第四个参数：`扩张半径`。这个参数会根据你指定的值去扩大或缩小投影尺寸，如果我们用一个负的扩张半径，而他的值刚好等于模糊半径，那么投影的尺寸就会与投影所属的元素尺寸完全一致，除非使用偏移量来移动他，否则我们将看不到任何投影
```css
.box{
    box-shadow: 7px 0 5px -5px #333;
}
```
